/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.poketrirx.twentyfourtyeighttester;

import com.poketrirx.twentyfourtyeighttester.impl.simulator.GameLogicImpl;
import com.poketrirx.twentyfourtyeighttester.impl.simulator.SimulatorImpl;
import com.poketrirx.twentyfourtyeighttester.impl.strategy.leftdown.LeftDownStrategy;
import com.poketrirx.twentyfourtyeighttester.pub.models.Summary;
import com.poketrirx.twentyfourtyeighttester.pub.simulation.Simulator;
import com.poketrirx.twentyfourtyeighttester.pub.strategy.Strategy;

public class App {
    public static void main(String[] args) {
        Simulator simulator = new SimulatorImpl(new GameLogicImpl());
        Strategy strategy = new LeftDownStrategy();

        Summary summary = simulator.simulate(strategy);

        printSummary(strategy.getName(), summary);
    }

    private static void printSummary(String name, Summary summary) {
        System.out.println(name);

        System.out.println(String.format("Max Block Size: %s", summary.getMaxBlockSize()));
        System.out.println(String.format("Max Score: %s", summary.getMaxScore()));
        System.out.println();
    }
}
